online_course_system/online_course_system/EmailOTPAuth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('dashboard.urls'), name='dashboard'),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls'), name='user'),
    path('course/', include('course.urls'), name='course'),
    path('student/', include('student.urls'), name='student'),
    path('teacher/', include('teacher.urls'), name='teacher'),
    # path('', include('payment.urls')),
    # path('payment/', include('payment.urls'), name='payment'),
]

online_course_system/online_course_system/teacher/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('index', views.index, name="index"),
    path('info', views.info, name="info"),
    path('add-course', views.add_course, name='add-course'),
    # path('updatecourse', views.updatecourse, name='updatecourse'),
    # path('updatecourse/<str:c_title>', views.updatecourse, name='updatecourse'),
    path('course_list', views.course_list, name='course_list'),
    path('search_value', views.search_value, name="search_value"),
    # path('deletecourse', views.deletecourse, name="deletecourse"),
    path('AddedCourse', views.AddedCourse, name='AddedCourse'),
    path('update', views.update_course, name='update'),
    path('delete', views.delete_course, name="delete"),
    path('update/<int:course_id>', views.update_course, name='update'),
    path('delete1/<int:course_id>', views.delete_course1, name="delete1"),
    path('Courses/<str:slug>', views.course_detail, name='course_detail'),
    path('add_section/<str:slug>', views.add_section, name='add_section'),
    path('add_lecture/<str:slug>', views.add_lecture, name='add_lecture'),
    path('added_content', views.added_content, name='added_content'),
    path('home1', views.home1, name="home1"),
]

online_course_system/online_course_system/user/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .views import signin, signup, reg_otp_view, login_otp_view, logout_view

urlpatterns = [
    path('signin', signin, name='login'),
    path('signup', signup, name='register'),
    path('signup/otp', reg_otp_view, name='otp'),
    path('login/otp', login_otp_view, name='otp'),
    # path('user_selection', user_selection, name="user_selection"),
    path('logout', logout_view, name="logout"),
    path('reset_password/', PasswordResetView.as_view(), name="reset_password"),
    path('reset_pass_sent/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset_pass_complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

online_course_system/online_course_system/course/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.utils.timezone import now
import string, random
from embed_video.fields import EmbedVideoField


def get_random_string(lenght):
    letter = string.ascii_letters
    return ''.join(random.choice(letter) for i in range(lenght))


# Create your models here.

COURSE_TYPE = [
    ("FREE", "FREE"),
    ("PAID", "PAID"),
]


class Course(models.Model):
    title = models.CharField(max_length=100,unique="True")
    description = models.TextField()
    thumbnail_url = models.CharField(max_length=100)
    course_type = models.CharField(max_length=4, choices=COURSE_TYPE, default="FREE")
    course_length = models.CharField(max_length=20)
    course_slug = models.SlugField(default="-")
    course_price = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.course_type} - {self.title}."

    def save(self, *args, **kwargs):
        self.course_slug = slugify(self.title)
        self.course_slug += f"-{get_random_string(10)}"
        if self.course_type == "FREE":
            course_price = 0
        super().save(*args, **kwargs)


class Section(models.Model):
    title = models.CharField(max_length=100)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title} - {self.course}"


LECTURE_TYPE = [
    ("PREMIUM", "PREMIUM"),
    ("NOT PREMIUM", "NOT PREMIUM"),
]


class Lecture(models.Model):
    title = models.CharField(max_length=100)
    video_url =EmbedVideoField()
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, blank=True)
    lecture_slug = models.SlugField(default="-")

    def save(self, *args, **kwargs):
        self.course = self.section.course
        self.lecture_slug = slugify(self.title)
        self.lecture_slug += f"-{get_random_string(10)}"
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.id} - {self.title} - {self.section}"


class LectureComment(models.Model):
    comment = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    lecture = models.ForeignKey(Lecture, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=now)

    def __str__(self):
        return f"{self.id} - {self.user.username} - {self.comment[0:15]} ..."


class PaymentProcess:
    def save(self):
        pass

#
# class StudentInfo(models.Model):
#     pass
#
#
# class CourseSubscription:
#     objects = None

online_course_system/online_course_system/teacher/models.py
from django.db import models
# from django.utils.text import slugify
from django.contrib.auth.models import User
from course.models import Course
# from django.utils.timezone import now
# import string, random
#
#
# def get_random_string(lenght):
#     letter = string.ascii_letters
#     return ''.join(random.choice(letter) for i in range(lenght))
#
#
# # Create your models here.
#
# COURSE_TYPE = [
#     ("FREE", "FREE"),
#     ("PAID", "PAID"),
# ]
#
#
# class Course(models.Model):
#     title = models.CharField(max_length=100)
#     description = models.TextField()
#     thumbnail_url = models.CharField(max_length=100)
#     course_type = models.CharField(max_length=4, choices=COURSE_TYPE, default="FREE")
#     course_length = models.CharField(max_length=20)
#     course_slug = models.SlugField(default="-")
#     course_price = models.IntegerField(default=0)
#
#     def __str__(self):
#         return f"{self.course_type} - {self.title}."
#
#     def save(self, *args, **kwargs):
#         self.course_slug = slugify(self.title)
#         self.course_slug += f"-{get_random_string(10)}"
#         if self.course_type == "FREE":
#             course_price = 0
#         super().save(*args, **kwargs)
#
#
# class Section(models.Model):
#     title = models.CharField(max_length=100)
#     course = models.ForeignKey(Course, on_delete=models.CASCADE)
#
#     def __str__(self):
#         return f"{self.title} - {self.course}"
#
#
# LECTURE_TYPE = [
#     ("PREMIUM", "PREMIUM"),
#     ("NOT PREMIUM", "NOT PREMIUM"),
# ]
#
#
# class Lecture(models.Model):
#     title = models.CharField(max_length=100)
#     video_url = models.CharField(max_length=100)
#     section = models.ForeignKey(Section, on_delete=models.CASCADE)
#     course = models.ForeignKey(Course, on_delete=models.CASCADE, blank=True)
#     lecture_slug = models.SlugField(default="-")
#     lecture_type = models.CharField(max_length=12, choices=LECTURE_TYPE, default="PREMIUM")
#
#     def save(self, *args, **kwargs):
#         self.course = self.section.course
#         self.lecture_slug = slugify(self.title)
#         self.lecture_slug += f"-{get_random_string(10)}"
#         if self.section.course.course_type == "FREE":
#             self.lecture_type = "NOT PREMIUM"
#         super().save(*args, **kwargs)
#
#     def __str__(self):
#         return f"{self.id} - {self.title} - {self.section} - {self.lecture_type}"
#
#
# # class LectureComment(models.Model):
# #    comment = models.TextField()
# #    user = models.ForeignKey(User, on_delete=models.CASCADE)
# #    lecture = models.ForeignKey(Lecture, on_delete=models.CASCADE)
# #    timestamp = models.DateTimeField(default=now)
#
# #    def __str__(self):
# #        return f"{self.id} - {self.user.username} - {self.comment[0:15]} ..."


class TeacherInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_id = models.EmailField(default="-")
    mobile_no = models.CharField(max_length=12)
    # dob = models.DateField()
    address = models.TextField()

    def __str__(self):
        return f"{self.user} - {self.user.email} - {self.mobile_no}"


class CourseAdded(models.Model):
    teacher = models.ForeignKey(TeacherInfo, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.teacher.user} ==== {self.course}"

online_course_system/online_course_system/teacher/views.py
from django.shortcuts import render, redirect
from course.models import Course, Lecture, Section
from django.db.models import Q
from .models import TeacherInfo, CourseAdded
from student.models import CourseSubscription, StudentInfo


# Create your views here.
def info(request):
    if request.user.is_authenticated == True:
        return render(request, "teacher/info.html")
    return redirect("home")


def index(request):
    return render(request, "teacher/index.html")


def add_course(request):
    context = {
        'title': 'add course'
    }
    if request.method == "POST":
        title = request.POST['title']
        description = request.POST['description']
        thumbnail_url = request.POST['thumbnail_url']
        course_type = request.POST['course_type']
        course_length = request.POST['course_length']
        # course_slug = request.POST['course_slug']
        course_price = request.POST['course_price']
        new_course = Course(title=title, description=description, thumbnail_url=thumbnail_url, course_type=course_type,
                            course_length=course_length, course_price=course_price)
        new_course.save()
        course = Course.objects.filter(title=title).first()
        teacher = TeacherInfo.objects.filter(user=request.user).first()
        new_sub = CourseAdded(teacher=teacher, course=course)
        new_sub.save()
        return redirect('AddedCourse')
    return render(request, 'teacher/add-course.html', context)


def AddedCourse(request):
    if request.user.is_authenticated == True:
        user1 = TeacherInfo.objects.filter(user=request.user).first()
        tcourse = CourseAdded.objects.filter(teacher=user1)
        contest = {
            "tcourse" : tcourse,
        }
        return render(request, "teacher/course_list.html", contest)
    return redirect("teacher/index.html")


# def added_content(request):
#     if request.user.is_authenticated == True:
#         user1 = TeacherInfo.objects.filter(user=request.user).first()
#         tcourse = CourseAdded.objects.filter(teacher=user1)
#         contest = {
#             "tcourse": tcourse,
#         }
#         return render(request, "teacher/course_list.html", contest)
#     return redirect("teacher/index.html")


def update_course(request):
    user1 = TeacherInfo.objects.filter(user=request.user).first()
    tcourse = CourseAdded.objects.filter(teacher=user1)
    contest = {
        "tcourse": tcourse,
    }
    # course_id = int(course_id)
    # context = {
    #     "course_id": course_id
    # }

    # try:
    #     course = Course.objects.get(id=course_id)
    # except Course.DoesNotExist:
    #     return redirect('index')
    if request.method == "POST":
        tocheck= request.POST['c_title']
        course = Course.objects.filter(title__icontains=tocheck).first()
        course.title = request.POST['title']
        course.description = request.POST['description']
        course.thumbnail_url = request.POST['thumbnail_url']
        course.course_type = request.POST['course_type']
        course.course_length = request.POST['course_length']
        # course_slug = request.POST['course_slug']
        course.course_price = request.POST['course_price']
        course.save()
        return redirect('AddedCourse')
    return render(request, 'teacher/update.html', contest)


# def updatecourse(request):
#     course = Course.objects.all()
#     context = {
#         "course": course
#     }
#     return render(request, 'teacher/update.html', context)


def delete_course(request):
    user1 = TeacherInfo.objects.filter(user=request.user).first()
    tcourse = CourseAdded.objects.filter(teacher=user1)
    context = {
        "tcourse": tcourse,
    }
    return render(request, "teacher/delete.html", context)


def added_content(request):
    user1 = TeacherInfo.objects.filter(user=request.user).first()
    tcourse = CourseAdded.objects.filter(teacher=user1)
    context = {
        "tcourse": tcourse,
    }
    return render(request, "teacher/added_content.html", context)


def delete_course1(request, course_id):
    course_id = int(course_id)
    try:
        course = Course.objects.filter(id=course_id)
    except Course.DoesNotExist:
        return redirect('index')
    course.delete()
    return redirect('delete')


def search_value(request):
    search_post = request.GET['q']
    course = Course.objects.filter(title__icontains=search_post)
    # If not searched, return default posts
    context = {
        'course': course
    }
    return render(request, 'course/courses.html',  context)


def course_list(request):
    # course = Course.objects.all()
    return redirect('AddedCourse')


def course_detail(request, slug):
    if not Course.objects.filter(course_slug=slug).exists():
        return render(request, '404.html')
    else:
        course = Course.objects.filter(course_slug=slug).first()
        section = Section.objects.filter(course=course)
        lecture = Lecture.objects.filter(course=course)
        if request.user.is_authenticated == True:
            subscription_course = CourseSubscription.objects.filter(student=StudentInfo.objects.filter
            (user=request.user).first(), course=course).first()
        else:
            subscription_course = None
        context = {
            "course": course,
            "section": section,
            "lecture": lecture,
            "subscription_course": subscription_course,
        }
        return render(request, 'course/course_detail.html', context)


def add_section(request,slug):
    user1 = TeacherInfo.objects.filter(user=request.user).first()
    tcourse = Course.objects.filter(course_slug=slug).first()
    contest = {
        "tcourse": tcourse,
    }
    if request.method == "POST":
        # tocheck = request.POST['c_title']
        # course = Course.objects.filter(title__icontains=tocheck).first()
        title = request.POST['title']
        sec = Section(title=title, course=tcourse)
        sec.save()
    return render(request, 'teacher/add_section.html', contest)


def add_lecture(request,slug):
    user1 = TeacherInfo.objects.filter(user=request.user).first()
    tcourse = Course.objects.filter(course_slug=slug).first()
    tsection = Section.objects.filter(course=tcourse)
    contest = {
        "tsection": tsection,
    }
    if request.method == "POST":
        # user1 = TeacherInfo.objects.filter(user=request.user).first()
        # tcourse = CourseAdded.objects.filter(teacher=user1)
        title=request.POST['title']
        video_url = request.POST['video_url']
        tocheck = request.POST['s_title']
        tsection = Section.objects.filter(title=tocheck).first()
        lec = Lecture(title=title, video_url=video_url, section=tsection, course=tcourse)
        lec.save()
        # ssection = Section.objects.filter(title=tocheck).first()
        # contest = {
        #     "ssection": ssection,
        # }
        return render(request, 'teacher/add_lecture.html', contest)
    return render(request, 'teacher/add_lecture.html',contest)


def home1(request):
    return render(request,'teacher/index.html')

online_course_system/online_course_system/templates/teacher/add-course.html
{% extends 'teacher/index.html' %}
{% load static %}
{% block title %}Add Course
{% endblock title %}
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% block head %}
   {% endblock head %}
  <style>
  html, body{
        min-height: 100% !important;
    }
    section{
        border-radius: 10px !important;
    }

    .showpassword {
      cursor: pointer;
    }

    .showpasswordsingup {
      cursor: pointer;
    }

    /*
 * Footer
 */
    .blog-footer {
      padding: 2.5rem 0;
      color: #999;
      text-align: center;
      background-color: #f9f9f9;
      border-top: .05rem solid #e5e5e5;
    }

    .blog-footer p:last-child {
      margin-bottom: 0;
    }
  </style>
</head>
{% block body %}
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom shadow-sm">
      <ul class="navbar-nav mr-auto">
                 <li class="nav-item active">
                     <a class="btn btn-basic focus:shadow-outline text-white" type="button" href="index{{ index }}">Back </a>
                 </li>
             </ul>
    <div class="container">
        <div class="container mx-auto flex flex-wrap p-1 flex-col md:flex-row items-center">
      <a class="navbar-brand" href="{% url 'home1' %}">HOME</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
           <a class="nav-link" href="{% url 'course_list' %}">Course Details</a>
        </li>
<!--          <li class="nav-item active">-->
<!--            <a class="nav-link" href="{% url 'pricing' %}"> Premium </a>-->
<!--          </li>-->

        </ul>
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
          <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="studentDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <img src="https://img.icons8.com/color/24/000000/user-male-circle.png"/> {{ request.user|upper }}
        </a>
        <div class="dropdown-menu" aria-labelledby="studentDropdown">
          <a class="dropdown-item" href="info{{ info }}">User Account</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        </div>
      </li>
          {% else %}
          <!--<li class="nav-item active">
             Button trigger modal
            <button type="button" class="btn btn-outline-success mx-2 my-1 btn-sm" data-toggle="modal"
              data-target="#loginModal">Login</button>
          </li>
          <li class="nav-item">
            <button type="button" class="btn btn-success mx-1 my-1 btn-sm" data-toggle="modal"
              data-target="#singupModal">Register</button>
          </li>-->
          {% endif %}
        </ul>
      </div>
    </div>
    </div>
  </nav>
  <div class="container-fluid">
    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="sidebar-sticky pt-3">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'add-course' %}">
                            <img src="https://cdn-icons-png.flaticon.com/24/2997/2997495.png" />
                            Add Course
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'update' %}">
                            <img src="https://cdn.iconscout.com/icon/premium/png-24-thumb/arrows-377-780707.png" />
                            Update Course
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'delete' %}">
                            <img src="https://cdn.iconscout.com/icon/free/png-24/delete-736-470378.png" />
                            Delete Course
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'added_content' %}">
                            <img src="https://cdn-icons-png.flaticon.com/24/2997/2997495.png" />
                            Add Content
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
        <!-- Content -->

  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
              <div id="content" class="colM">
                  <br><h1>Add Course</h1>
                  <br
          <div id="content-main">
                  <form class="w-full max-w-sm" method="post" >{% csrf_token %}
        <div class="row">
        <div class="col-md-1"></div>
            <div class="col-md-4">
                <fieldset class="module aligned ">
                    <div class="form-row field-title">
                        <div class="form-group">
                            <label class="required" for="id_title">Title:</label>
                            <input type="text" name="title" class="form-control form-control-md vTextField" maxlength="100" required="" id="id_title">
                        </div>
                    </div>
                    <div class="form-row field-description">
                        <div class="form-group">
                            <label class="required" for="id_description">Description:</label>
                            <textarea name="description" cols="40" rows="4" class="form-control vLargeTextField" required="" id="id_description"></textarea>
                        </div>
                    </div>
                    <div class="form-row field-thumbnail_url">
                        <div class="form-group">
                            <label class="required" for="id_thumbnail_url">Thumbnail url:</label>
                            <input type="text" name="thumbnail_url" class="form-control form-control-md vTextField" maxlength="100" required="" id="id_thumbnail_url">
                        </div>
                    </div>
                    <div class="form-row field-course_type">
                        <div class="form-group">
                            <label class="required" for="id_course_type">Course type:</label>
                            <select name="course_type" class="form-control form-control-md" id="id_course_type">
                                <option value="FREE" selected="">FREE</option>
                                <option value="PAID">PAID</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-row field-course_length">
                        <div class="form-group">
                            <label class="required" for="id_course_length">Course length:</label>
                            <input type="text" name="course_length" class="form-control form-control-md vTextField" maxlength="20" required="" id="id_course_length">
                        </div>
                    </div>
                    <div class="form-row field-course_price">
                        <div class="form-group">
                            <label class="required" for="id_course_price">Course price:</label>
                            <input type="number" name="course_price" value="0" class="form-control form-control-md vIntegerField" required="" id="id_course_price">
                        </div>
                    </div>
                </fieldset>
                <!--<fieldset class="module aligned ">
                <div class="form-row field-course_slug">
                 <div>
                <label>Course slug:</label>
                <div class="readonly">-</div>
                 </div>
                 </div>
                 </fieldset>-->
                <div class="submit-row">
                    <input type="submit" value="Save" class="btn btn-info" name="_save">
                    <input type="submit" value="Save and add another" class="btn btn-info" name="addanother">
                    <!--<input type="submit" value="Save and continue editing" class="btn btn-info" name="_continue">-->
                </div>
            </div>
        </div>
    </form>
              </div>
<canvas class="my-3 w-80 chartjs-render-monitor" id="myChart" width="1080" height="20"
        style="display: block; width: 1080px; height: 20px;"></canvas>
              </div>
  </main>
    </div>
  </div>



<!--<footer class="blog-footer"style="position: fixed; width: 100vw;">
    <p>Made with ❤ by <a href="https://twitter.com">@Online course</a></p>
    <p>
      <a href="#">Back to top</a>
    </p>
  </footer>-->

  <!-- Optional JavaScript -->
  {% if user.is_authenticated %}{% else %}
  <script type="text/javascript" src="{% static 'js/validation.js' %}"></script>
  {% endif %}
     <!--jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"></script>
{% block js %}
{% endblock js %}
{% endblock body %}
  </div>
</body>